### ISSUE TITLE
Project-wide lint

### ISSUE THREAD

**Issue by Gert-dev** [mehcode/linter-ui-plus#16]
I develop a linter plugin package (for PHP) myself, and one of the things that I've always missed is the ability to do a project-wide (or possibly a folder-confined) lint. I fantasize about being able to right-click a folder in the tree view and selecting `Lint Directory`, after which all the files in the folder are requested to be linted by the providers and after which the results are displayed in the UI (much like the results view of `Search in Directory`, for textual searching, has).

I'm not sure if this package is even the right place for this, as I believe `linter` handles the actual linting. However, I thought I'd post it anyways, seeing as it's mostly UI-related and doesn't require any new functionality from linter (it's basically looping over files, calling `lint` as is currently done when modifying a single file and showing the results in the UI package). Also, this package seems to have the ideal visualization for it in the dock with its ability to collapse the message and clear distinction of errors in separate files.

IDE's such as PhpStorm (IntelliJ/IDEA) also offer this kind of folder linting. It would be fantastic if you installed a new linter and want to see what it has to say over your existing project. Or perhaps you copy-pasted some code from another codebase and want to run the linter to see if any dependencies are missing or the code style is consistent.

Thanks!

**Comment by Arcanemagus** [comment]
`linter` is definitely the correct place for this, there is already an issue open there on this I believe.

**Comment by Gert-dev** [comment]
Thanks for your response. Do you by any chance have a link to the appropriate issue? I've been scanning the issue list of `linter`, but [they seem to be of the opinion that it's not their responsibility](https://github.com/steelbrain/linter/issues/739#issuecomment-124883038) (and so it begins... 😄).

I can understand they want to delegate this to another package as the core functionality for it is already in place (someone just has to expose the UI and do the actual looping). Unless I'm wrong and it isn't, in which case I can understand why you may want to send it back to `linter` 😄.

I had been thinking about implementing this in my linter, but that would limit it to my specific linter (and I'm hoping to eventually move to being a [language server client](https://github.com/atom/atom-languageclient)), which seems a bit unfortunate as undoubtedly other linter providers can also benefit from this.

**Comment by mehcode** [comment]
@Gert-dev I would actually reach to say this is a `php-integrator` problem. Linter Indie V2 (which is the standard that the Atom team is going to support along with the new LSP) supports project wide linting. There's nothing stopping you from linting the whole project in the background and sending those messages along. As an example, the `flow-ide` package supports this.

I'm of the opinion that linting should be project-wide at all times and the UI should filter down for the user when requested.

**Comment by Arcanemagus** [comment]
@Gert-dev Actually, that's probably the issue I was thinking of.

The biggest problem with doing this in `linter` is that it requires a `TextEditor`... which means _every_ file linted would need to be opened in Atom. As I (apparently) said in that thread, this is better handled with the `build` infrastructure, or even better by making the providers themselves project wide (_if_ that makes sense for them, for most it doesn't!) as @mehcode said.
